spring:
  datasource:
    url: jdbc:sqlserver://10.2.111.21:1522;databaseName=restapi;trustServerCertificate=true
    username: wundr2
    password: wundr
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
server:
  port: 8080